repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in staged files before commit or push.
        entry: bash -c 'git diff --cached --name-only | xargs -r trufflehog filesystem --fail --no-update --only-verified'
        language: system
        stages: ["pre-commit", "pre-push"]
