version: "3.8"

services:
  index:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run dev
    env_file:
      - ./.env
    ports:
      - "3300:3300"
    volumes:
      - .:/usr/src/index
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
